name: Friends Network Update

on:
  schedule:
    - cron: "30 0 */3 * *"  # 每3天运行一次，错开30分钟
  workflow_dispatch:        # 允许手动触发
  push:
    branches: ["main"] # main分支推送时触发
    paths:
      - "assets/friends/friends.json"
      - "src/friends/**"
      - ".github/workflows/friends.yml"

jobs:
  update-friends:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          
      # 创建必要的目录
      - name: Create required directories
        run: |
          mkdir -p assets/friends/avatars
          mkdir -p assets/friends/generated
          
      # 安装系统依赖
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
          
      # 设置Node环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      # 安装依赖
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
          
      # 配置Git并拉取最新 main
      - name: Configure Git and Pull Latest main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main --rebase

      # 生成朋友网络
      - name: Generate friends network
        run: node src/friends/generate-friends.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 提交更改到 main 分支
      - name: Commit and Push Changes to main
        run: |
          git add assets/friends/
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update friends network"
          git push origin main